sudo: false

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers

language: scala
scala:
  - 2.10.6
jdk:
   - oraclejdk8
script:
   - sbt test testFunctional
   - sbt -Dmima.testScalaVersion="2.11.7" testFunctional
   - sbt -Dmima.testScalaVersion="2.12.0-M3" testFunctional
