sudo: false

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers

language: scala

scala:
  - 2.10.6

jdk:
  - oraclejdk8

env:
  matrix:
    - TEST_COMMAND="test"
    - TEST_COMMAND="scripted"
    - TEST_COMMAND="testFunctional"
    - TEST_COMMAND="-Dmima.testScalaVersion=2.11.11 testFunctional"
    - TEST_COMMAND="-Dmima.testScalaVersion=2.12.3 testFunctional"
    - TEST_COMMAND="it:test"
    - TEST_COMMAND="mimaReportBinaryIssues"
    - TEST_COMMAND="-Dmima.buildScalaVersion=2.12.3 ^^1.0.0-RC3 test"
    - TEST_COMMAND="-Dmima.buildScalaVersion=2.12.3 ^^1.0.0-RC3 scripted"
    - TEST_COMMAND="-Dmima.buildScalaVersion=2.12.3 testFunctional"
    - TEST_COMMAND="-Dmima.buildScalaVersion=2.12.3 it:test"
    - TEST_COMMAND="-Dmima.buildScalaVersion=2.12.3 ^^1.0.0-RC3 mimaReportBinaryIssues"

script:
  - sbt $TEST_COMMAND

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
